[package]
name = "astrix-consensusmanager"
description = "Astrix consensus library"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
duration-string.workspace = true
futures-util.workspace = true
futures.workspace = true
itertools.workspace = true
astrix-consensus-core.workspace = true
astrix-consensus-notify.workspace = true
astrix-core.workspace = true
astrix-utils.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
tokio.workspace = true
